### PR TITLE
Feature/remove outliers

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
Hi,
I have added two new ways to remove outliers, this can help removing noise from a point cloud. 

- statistical outlier removal
- radius outlier removal
- added an `invert` flag for the `select_down_sample`, this returns a point cloud with all the indices in the input array removed

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/565)

### CODE REVIEW

**Comment by qianyizh** [comment]
This looks pretty awesome. @syncle can you take a look?
@yxlao can you check the change in generate.h part and see if it makes sense?

**Comment by nicolas-chaulet** [comment]
@yxlao actually I did not mean to change the generate.sh, let me fix that

**Comment by yxlao** [comment]
Thanks for the contribution @nicolas-chaulet! The reverted `generate.sh` looks good

**Comment by syncle** [comment]
This PR is great overall. I just commented minor change requests. Another point is if we have tutorial example, we will need this in the documentation. @nicolas-chaulet Could you also work on this?

**Comment by syncle** [comment]
Thanks for the update @nicolas-chaulet! I would like to bold this feature by making a separate tutorial script. I would like to push some commits for this in your branch. (can I do this?)

**Comment by nicolas-chaulet** [comment]
@syncle no worries, please go ahead and thanks for asking!

**Comment by syncle** [comment]
I just finished polishing. I think this PR is ready to be merged. Thanks @nicolas-chaulet!

**Pull request merged**
