### PR TITLE
Eigen Alignment support

### PR DESCRIPTION
**Pull request by morrisfranken**
This commit adds Eigen Alignment support to Open3D. See #653 for more details.
While I have run the unitTests on my computer, I do not know for sure if it does not break anything else. Nor am I able to test this on Windows/Mac. If anyone else would be able to verify this commit would not break anyhthing else, please do so.

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/654)

### CODE REVIEW

**Comment by yxlao** [comment]
Thanks @morrisfranken ! 
The mac build is failing, while we're in the review proces, could you please fix this issue, following https://github.com/JakobEngel/dso/issues/111?

The fix would roughly be like this:
```
diff --git a/src/Core/Geometry/DownSample.cpp b/src/Core/Geometry/DownSample.cpp
index d38e404a..d6398ae0 100644
--- a/src/Core/Geometry/DownSample.cpp
+++ b/src/Core/Geometry/DownSample.cpp
@@ -154,7 +154,8 @@ std::shared_ptr<PointCloud> VoxelDownSample(const PointCloud &input,
     std::unordered_map<Eigen::Vector3i, AccumulatedPoint,
             hash_eigen::hash<Eigen::Vector3i>,
             std::equal_to<Eigen::Vector3i>,
-            Eigen::aligned_allocator<std::pair<Eigen::Vector3i, AccumulatedPoint>>> voxelindex_to_accpoint;
+            Eigen::aligned_allocator<std::pair<const Eigen::Vector3i, AccumulatedPoint>>>
+            voxelindex_to_accpoint;
     Eigen::Vector3d ref_coord;
     Eigen::Vector3i voxel_index;
     for (int i = 0; i < (int)input.points_.size(); i++) {
diff --git a/src/Core/Integration/ScalableTSDFVolume.cpp b/src/Core/Integration/ScalableTSDFVolume.cpp
index 26492dfd..1b93c34f 100644
--- a/src/Core/Integration/ScalableTSDFVolume.cpp
+++ b/src/Core/Integration/ScalableTSDFVolume.cpp
@@ -206,7 +206,8 @@ std::shared_ptr<TriangleMesh> ScalableTSDFVolume::ExtractTriangleMesh()
     std::unordered_map<Eigen::Vector4i, int,
             hash_eigen::hash<Eigen::Vector4i>,
             std::equal_to<Eigen::Vector4i>,
-            Eigen::aligned_allocator<std::pair<Eigen::Vector4i, int>>> edgeindex_to_vertexindex;
+            Eigen::aligned_allocator<std::pair<const Eigen::Vector4i, int>>>
+            edgeindex_to_vertexindex;
     int edge_to_index[12];
     for (const auto &unit : volume_units_) {
         if (unit.second.volume_) {
diff --git a/src/Core/Integration/ScalableTSDFVolume.h b/src/Core/Integration/ScalableTSDFVolume.h
index 07360e6e..eec74728 100644
--- a/src/Core/Integration/ScalableTSDFVolume.h
+++ b/src/Core/Integration/ScalableTSDFVolume.h
@@ -89,7 +89,8 @@ public:
     std::unordered_map<Eigen::Vector3i, VolumeUnit,
             hash_eigen::hash<Eigen::Vector3i>,
             std::equal_to<Eigen::Vector3i>,
-            Eigen::aligned_allocator<std::pair<Eigen::Vector3i, VolumeUnit>>> volume_units_;
+            Eigen::aligned_allocator<std::pair<const Eigen::Vector3i, VolumeUnit>>>
+            volume_units_;

 private:
     Eigen::Vector3i LocateVolumeUnit(const Eigen::Vector3d &point) {
diff --git a/src/Core/Integration/UniformTSDFVolume.cpp b/src/Core/Integration/UniformTSDFVolume.cpp
index 2857e9a9..d6a6f9a1 100644
--- a/src/Core/Integration/UniformTSDFVolume.cpp
+++ b/src/Core/Integration/UniformTSDFVolume.cpp
@@ -155,7 +155,7 @@ std::shared_ptr<TriangleMesh> UniformTSDFVolume::ExtractTriangleMesh()
     std::unordered_map<Eigen::Vector4i, int,
             hash_eigen::hash<Eigen::Vector4i>,
             std::equal_to<Eigen::Vector4i>,
-            Eigen::aligned_allocator<std::pair<Eigen::Vector4i, int>>>
+            Eigen::aligned_allocator<std::pair<const Eigen::Vector4i, int>>>
             edgeindex_to_vertexindex;
     int edge_to_index[12];
     for (int x = 0; x < resolution_ - 1; x++) {```

**Comment by morrisfranken** [comment]
@yxlao Thanks! It now compiles on Mac as wel.

**Comment by qianyizh** [comment]
Another question: I still cannot reproduce the Eigen alignment issue on my machine. @yxlao is it possible to set up a similar environment in CI to duplicate the segfault? So in the future we can always check it automatically with CI.

**Comment by takanokage** [comment]
As I mentioned in #653, the issue is reproducible when using `emplace_back` rather than `push_back`. `emplace_back` is not used in the Open3D/master code which explains why we haven't seen the issue before.

From my previous experience (though not with Eigen specifically) using misaligned memory can lead to performance issues rather than errors/crashes.

At this time, given my limited understanding of the issue, I'm am not sure this PR fixes an actual problem with the existing Open3D code.

I do expect that in the future, once we have performance tests in place, we will need to address any alignment issues.

**Comment by morrisfranken** [comment]
I would like to stress that this issue is not limited to `emplace_back`, as explained in a later post in #653, and does cause undefined behaviour leading up to potential segfaults. The documentation from Eigen is clear that `std::vector`, `std::map` and other STL containers must use the `Eigen::allocator` (http://eigen.tuxfamily.org/dox/group__TopicStlContainers.html)

You raised a good point regarding `Vector3d` and other non vectorizable types. I can solve those in the PR. 

But I personally don't see why not to fix the issue once and for all. I would like to avoid others having to go through the same struggle finding the root of a segfault when we already know that using Eigen in STL containers without allocators may potentially be the cause of it. Having said that, it would be ok to wait for sufficient unit-test coverage to make sure nothing else breaks.

**Comment by takanokage** [comment]
@morrisfranken Your contribution is valuable and highly appreciated. Just wondering about the safest way to integrate your work.

Let's do it this way:
1. @qianyizh still has some suggestions (mainly the 80 col wraparound). Fix those.
2. In parallel I'll get your code and test it locally. Does that sound good?

**Comment by takanokage** [comment]
Here's an example on how you can use aliasing to reduce line width and help adhere to the 80 col guideline without splitting lines:

Original code (88 cols):
```
std::vector<Eigen::Matrix4d, Eigen::aligned_allocator<Eigen::Matrix4d>> extrinsic_;
```

Proposed code (70 cols):
```
using Matrix4d_allocator = Eigen::aligned_allocator<Eigen::Matrix4d>;
...
std::vector<Eigen::Matrix4d, Matrix4d_allocator> extrinsic_;
```

**Comment by morrisfranken** [comment]
@takanokage thanks and that sound like a good plan.

I really like the suggestion to put the allocator definition elsewhere to keep the lines within 80 characters. 

I'll make sure to use the allocator only for types that require it and I'm considering to use `Eigen::DontAlign` for Eigen types in classes to avoid the different size issue mentioned in the second half of #653

**Comment by morrisfranken** [comment]
This commit will fix a number of issues:
  - removes the Eigen allocator for types that do not require it
  - Applied changes requested by @qianyizh and @takanokage 
  - `Eigen::DontAlign` is added to matrices in classes to fix the issue regarding mismatching class-sizes with different compilation flags
    - PoseGraphNode
    - PoseGraphEdge
    - RegistrationResult
    - AlignmentSession
  - Duplicated functions to accept `Eigen::DontAlign`-matrices: 
    - EigenMatrix4dFromJsonArray
    - EigenMatrix6dFromJsonArray

Some notes:
  - I removed the alignment for `pybind_eigen_vector_of_vector`, since none of the template types currently require it. If that changes, the function should also be updated updated accordingly. 
  - the `pybind_eigen_vector_of_matrix` function does support Eigen Alignment, but I had not added that to the `repr_name` on line 244 in `open3d_eigen.cpp`, because I am not sure what the implications would be.

**Comment by takanokage** [comment]
___
*[src/UnitTest/UnitTest.h, line 52 at r4](https://reviewable.io/reviews/intelvcl/open3d/654#-LTP1F_M7YiPSrRXSwGo:-LTP1F_M7YiPSrRXSwGp:bbprh0q) ([raw file](https://github.com/intelvcl/open3d/blob/5ef8bca7c00ec802240238b7b596ceda523ef8c0/src/UnitTest/UnitTest.h#L52)):*
> ```objc
> 
>     // Equal test.
>     template<class T, int M, int N, int A>
> ```

Could you please explain the introduction of the new template argument?
I can understand it's a placeholder for the alignment option but at the first glance it compiles fine without it.

**Comment by takanokage** [comment]
___
*[src/Core/Utility/IJsonConvertible.cpp, line 163 at r3](https://reviewable.io/reviews/intelvcl/open3d/654#-LRiCCXcBxVPPSM0NwYN:-LTP1YmN80DMKGmhI-RT:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/0412f52c657fcfbd478e0f65237ed4d85e205aa5/src/Core/Utility/IJsonConvertible.cpp#L163)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

Please add unit test.
Please add EigenMatrix6dToJsonArray(Eigen::Matrix6d_u&,...).
</blockquote></details>

Done.

**Comment by takanokage** [comment]
___
*[src/Core/Registration/PoseGraph.h, line 48 at r2](https://reviewable.io/reviews/intelvcl/open3d/654#-LQHuNbd36WR7xCSXpz2:-LTP1_p29j4wt6fbrrFX:bb6un1j) ([raw file](https://github.com/intelvcl/open3d/blob/aaf985f7188616d34d513417ee3ffdbf890729a3/src/Core/Registration/PoseGraph.h#L48)):*
<details><summary><i>Previously, qianyizh (Qianyi Zhou) wrote…</i></summary><blockquote>

can you remove the extra indent in this file?
</blockquote></details>

Done

**Comment by takanokage** [comment]
___
*[src/Core/Odometry/RGBDOdometryJacobian.h, line 81 at r3](https://reviewable.io/reviews/intelvcl/open3d/654#-LRiBpOl-Bquw7I6-mnz:-LTP1bXv-lp8s2w-dzJ-:bb6un1j) ([raw file](https://github.com/intelvcl/open3d/blob/0412f52c657fcfbd478e0f65237ed4d85e205aa5/src/Core/Odometry/RGBDOdometryJacobian.h#L81)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

trim trailing whitespace
</blockquote></details>

Done

**Comment by takanokage** [comment]
___
*[src/Core/Odometry/RGBDOdometryJacobian.h, line 104 at r3](https://reviewable.io/reviews/intelvcl/open3d/654#-LRiBq4FCgj-NO59A-pY:-LTP1cTj9wZZ0tRpjBf_:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/0412f52c657fcfbd478e0f65237ed4d85e205aa5/src/Core/Odometry/RGBDOdometryJacobian.h#L104)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

trim trailing whitespace
</blockquote></details>

Done.

**Comment by takanokage** [comment]
___
*[src/Core/Geometry/DownSample.cpp, line 271 at r3](https://reviewable.io/reviews/intelvcl/open3d/654#-LRiBbpz4iWuQQR_Zs5Q:-LTP1gNTCke-rlCuxIha:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/0412f52c657fcfbd478e0f65237ed4d85e205aa5/src/Core/Geometry/DownSample.cpp#L271)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

trim trailing whitespace.

This can be made a default action in Visual Studio Code on saving a file.
</blockquote></details>

Done.

**Comment by takanokage** [comment]
___
*[src/Core/Odometry/Odometry.cpp, line 408 at r2](https://reviewable.io/reviews/intelvcl/open3d/654#-LQHsmS44r57V6pACLPE:-LTOz0gl3a6y6kDE2h7H:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/aaf985f7188616d34d513417ee3ffdbf890729a3/src/Core/Odometry/Odometry.cpp#L408)):*
<details><summary><i>Previously, qianyizh (Qianyi Zhou) wrote…</i></summary><blockquote>

Can you make sure the lines are fit into 80 char limits after all the changes?
So it is friendly to people who are using terminal based IDE.
</blockquote></details>

Done.

**Comment by takanokage** [comment]
___
*[src/Core/Odometry/RGBDOdometryJacobian.h, line 42 at r2](https://reviewable.io/reviews/intelvcl/open3d/654#-LQHtJM51R_3lzjp9fUG:-LTOz35Z7UOnj2Yd9GAU:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/aaf985f7188616d34d513417ee3ffdbf890729a3/src/Core/Odometry/RGBDOdometryJacobian.h#L42)):*
<details><summary><i>Previously, qianyizh (Qianyi Zhou) wrote…</i></summary><blockquote>

Same as above, please break the lines when they exceeds 80 chars.
And henceforth.
</blockquote></details>

Done.

**Comment by takanokage** [comment]
___
*[src/Visualization/Visualizer/ViewTrajectory.h, line 92 at r3](https://reviewable.io/reviews/intelvcl/open3d/654#-LRiZbxCDItKeMy5r3GD:-LTP26II0bS_hJF48YSA:b-896fix) ([raw file](https://github.com/intelvcl/open3d/blob/0412f52c657fcfbd478e0f65237ed4d85e205aa5/src/Visualization/Visualizer/ViewTrajectory.h#L92)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

trim trailing whitespace
</blockquote></details>

Done.

**Comment by takanokage** [comment]
Hi,

I made a few minor changes starting from your code.
The last question I have is about the introduction of the 'int A' argument in the template defs for ExpectEQ/LE/GE. The code compiles just fine with/without this (aka it doesn't appear to do anything at first glance) so why the change?

**Comment by takanokage** [comment]
The recent changed moved the `3rdparty` folder outside of Open3D. The `3rdparty` code is cloned using the `--recursive` argument.
I can't figure out, at a first glance, why it's failing. I need more time.

**Pull request merged**
