### PR TITLE
Docker test

### PR DESCRIPTION
**Pull request by takanokage**
This PR addresses the request to implement Open3D testing under Docker.

Following is a simplified list of tasks performed towards this PR:  

- Create Docker images for the following configurations:
  - Ubuntu:
    - 14.04
    - 16.04
    - 18.04.
  - Python installations:
    - py2: python2.x
    - py3: python3.x
    - mc2: miniconda2
    - mc3: miniconda3
  - Preinstalled dependencies:
    - base: minimal, dependencies will be built from source
    - deps: all dependencies are installed from packages
- Add scripts for building all images
- Add script for cloning, building and testing 
- Add script for performing all tests
- When building an image build the images it depends on
- Redesign command line args for building/testing images.
- Centralize the definition of the command line args for building/testing images.
- Add command line args to the script that clones/builds/tests Open3D.
- Install dependencies required to build Open3D using miniconda 2/3 environment.
- Fix building conda package.
- Build Python package
- Build Conda package
- Clone Open3D on the host, once, use for all build tests.
- Add tests for both static and shared builds (clone once - test twice)
- Use Docker ARGs to set the dockerfile variables programmatically
- Merge identical dockerfiles.
- Create scripts for uploading to docker hub.
- Upload images to docker hub
- Update the tests to use uploaded images rather than building them from scratch
- Test new TraviCI script on my fork using the uploaded images
- Make scripts run-able from any workdir
- Move logic from dockerfiles to dedicated setup scripts
- Modify docker container command prompt to display hostname:basename(crt_dir)$ (edit .bashrc file).
- Simplify the output of the scripts.
- Investigate solutions to avoid container name collisions for concurrent tests.
- Update the original .travis.yml file to allow docker and native builds at the same time.
- Help the user know at a glance which are native builds and which are docker builds.
- Test install/uninstall Open3D.
- Add timing for the image download.
- Investigate the possibility to use the travis-ci existing clone of Open3D for docker build tests.
- Upload images to Open3D repo on hub.docker.com
- Write documentation.

Testing the C++ project doesn't work due to a bug (cmake can't find Open3D installed under docker). This task will be addressed in a different PR.

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/773)

### CODE REVIEW

**Comment by takanokage** [comment]
I added the test for building a C++ example with installed Open3D.

Running 'cmake --find-package -DNAME=Open3D....' still has a bug however 'find_package(Open3D)' runs fine inside a CMakeLists.txt.

With this addition the docker tests are performing all the tests we used to run in TravisCI, and in addition they also test building the pip and conda packages.

**Comment by takanokage** [comment]
___
*[util/docker/open3d-test/setup/googletest-release-1.8.0.tar.gz, line  at r1](https://reviewable.io/reviews/intelvcl/open3d/773#-LWHzpEO46Og_4FHkjKU:-LWM6Chs7k1ba9VVBKdJ:b-7om340) ([raw file](https://github.com/intelvcl/open3d/blob/bf3cf899c6dd6bcf3893ab3b11bd5545b2b129f4/util/docker/open3d-test/setup/googletest-release-1.8.0.tar.gz#L)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

I have very good reasons why this way: the images are prebuilt. In other words no docker image setup time is necessary when running the tests.
If we do it the way you suggest the test time is increased to account for setting up the docker image.
I hope we all agree it is much better this way.
</blockquote></details>

I'd like to mention that most of the files that I include in the docker images are there temporarily only.
One of the main guidelines when building a docker image is to keep the image size to a minimum.
All the setup files, including any archives/binaries, are removed once the setup phase is completed.

**Comment by takanokage** [comment]
___
*[util/docker/open3d-test/Dockerfiles/Dockerfile-base, line 11 at r1](https://reviewable.io/reviews/intelvcl/open3d/773#-LWI4WQTAS2xqI88FIRH:-LWQGOofDjzQIiCPz-JE:b4ff5f7) ([raw file](https://github.com/intelvcl/open3d/blob/bf3cf899c6dd6bcf3893ab3b11bd5545b2b129f4/util/docker/open3d-test/Dockerfiles/Dockerfile-base#L11)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

why would I avoid tar.gz?
</blockquote></details>

My apologies.
I finally understood, tx to Jaesik, what you guys meant here.
I have moved the gtest src code to the 3rdparty folder.

**Comment by takanokage** [comment]
___
*[util/docker/open3d-test/setup/googletest-release-1.8.0.tar.gz, line  at r1](https://reviewable.io/reviews/intelvcl/open3d/773#-LWHzpEO46Og_4FHkjKU:-LWQGeryC_sFR2cYiLZi:b-n2p7ph) ([raw file](https://github.com/intelvcl/open3d/blob/bf3cf899c6dd6bcf3893ab3b11bd5545b2b129f4/util/docker/open3d-test/setup/googletest-release-1.8.0.tar.gz#L)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

I'd like to mention that most of the files that I include in the docker images are there temporarily only.
One of the main guidelines when building a docker image is to keep the image size to a minimum.
All the setup files, including any archives/binaries, are removed once the setup phase is completed.
</blockquote></details>

gtest src archive moved to 3rdparty.

**Comment by takanokage** [comment]
___
*[.travis.yml, line 6 at r1](https://reviewable.io/reviews/intelvcl/open3d/773#-LWHud4O6l__c84RyCLM:-LWS1Ff-CENAvDEb27aG:b-k6dlv) ([raw file](https://github.com/intelvcl/open3d/blob/bf3cf899c6dd6bcf3893ab3b11bd5545b2b129f4/.travis.yml#L6)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Do we know the return value of `sysctl -n hw.ncpu` on travis? If it is > 2 then it might potentially help with the mac build speed. We could do a test to find that out.
</blockquote></details>

Yeah, we could do that but it's not the scope of this PR. This is only about Docker testing.
We shouldn't delay this PR for things on our wishlist. This PR is complete.

**Comment by takanokage** [comment]
___
*[util/docker/open3d-test/setup/install-gtest.sh, line 25 at r4](https://reviewable.io/reviews/intelvcl/open3d/773#-LWRu5sv5ZT2e6gllMke:-LWS1ztY33z19Ghmfpvz:b-ycb6rx) ([raw file](https://github.com/intelvcl/open3d/blob/16f7954639f6b9d0891e57b21823641feb8cf35a/util/docker/open3d-test/setup/install-gtest.sh#L25)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Can you make sure that the tar.gz file is not deleted after this line? That is, we should keep the 3rd party directory untouched.
</blockquote></details>

the code here is run inside a docker image, it doesn't touch host files.

**Comment by takanokage** [comment]
___
*[util/docker/open3d-test/setup/test.sh, line 2 at r4](https://reviewable.io/reviews/intelvcl/open3d/773#-LWS0pycA7mD4tXzDlXC:-LWS1m5n8FYNhDM6YWgX:b-14x8sq) ([raw file](https://github.com/intelvcl/open3d/blob/16f7954639f6b9d0891e57b21823641feb8cf35a/util/docker/open3d-test/setup/test.sh#L2)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Consider adding `set -eu` to all test related shell scripts as we discussed.
</blockquote></details>

I apologize, personally I don't remember this discussion and I don't see how this helps this PR.

**Comment by takanokage** [comment]
___
*[util/scripts/setup-osx.sh, line 3 at r4](https://reviewable.io/reviews/intelvcl/open3d/773#-LWRzF4l0AD0kthzMDgR:-LWSOMN7Bew8J7wajvHw:br7qn92) ([raw file](https://github.com/intelvcl/open3d/blob/16f7954639f6b9d0891e57b21823641feb8cf35a/util/scripts/setup-osx.sh#L3)):*
<details><summary><i>Previously, takanokage (Dan Petre) wrote…</i></summary><blockquote>

well, I'm doubting myself, let me double check.
</blockquote></details>

As far as I can tell those error messages were not introduced by my PR and have to do with travis.
I can see them in other PRs too:
https://travis-ci.org/IntelVCL/Open3D/jobs/480990613#L1992
https://travis-ci.org/IntelVCL/Open3D/jobs/480698224#L1992

I have no ideas at the moment.

**Comment by yxlao** [comment]
If the particular error is not introduced in ths PR, one thing we can do is to enable `set -e` globally, and mask out that line explicitly:
```
command || true
```
and add a task to fix it later.

**Comment by takanokage** [comment]
I'm not sure about setting -e globally. It would seem that 'set -e' produced some unexpected behavior on the scripts installing the linux/macos dependencies.

At the moment the main place where we might need `set -e` is `util/scripts/run-travis.sh`.
This ensures we keep the right behavior for linux/macos build tests.

The second place where `set -e` may help is `util/open3d-test/setup/test.sh` which runs inside the docker images.
However updating `util/open3d-test/setup/test.sh` requires rebuilding/testing/uploading all the docker images which may take 4-5h.

**Comment by takanokage** [comment]
I already started the building/uploading/testing process after the latest changes.

**Comment by takanokage** [comment]
built & uploaded all docker images.

**Pull request merged**
