### PR TITLE
simplify the creation of a custom C++ project

### PR DESCRIPTION
**Pull request by takanokage**
Polished the CMake system in order to simplify the creation of a custom C++ project.
Now the CMakeLists.txt of a custom C++ project only needs to find Open3D and the required headers, libraries and library directories are automatically provided for both Open3D and its external dependencies.

### CODE REVIEW

**Comment by syncle** [comment]
Can you also check xcode build? I got some issue with this branch.
```
clang: error: no such file or directory: ~/Open3D/build-xcode/lib/Debug/libOpen3D.a
```
When building `MergeMesh` application.

**Comment by qianyizh** [comment]
This is pretty awesome. I like short CMakeLists files for external C++ programs. I will test this PR tonight.

**Comment by syncle** [comment]
I tried to compile this PR with XCode. For example, 
```
cmake -G Xcode ../src -DCMAKE_INSTALL_PREFIX=~/open3d_install
```
and I got a compile error aforementioned.

**Comment by takanokage** [comment]
This seems to be a CMake bug manifested when using object libraries together with Xcode.
I propose we open a separate issue for that and move with the current PR as is. The solution might not be as simple as not using object libraries because this is the mechanism that I was hoping to use to fix #393.

- [supporting link1](https://cmake.org/pipermail/cmake/2016-April/063169.html)
- [supporting link2](https://cmake.org/Bug/view.php?id=14768)
- [supporting link3](https://github.com/tensorflow/tensorflow/issues/15369)
- [supporting link4](https://gitlab.kitware.com/cmake/cmake/issues/17500)

**Comment by syncle** [comment]
I got it. I approve merge.

**Pull request merged**
