### PR TITLE
ColorMapOptimization

### PR DESCRIPTION
**Pull request by takanokage**
~~I had to breakdown the original ColorMapOptimization.cpp into three test cases, each in their own .h/.cpp files:~~
~~- ColorMapOptimization~~
~~- ColorMapOptimizationOption~~
~~- ImageWarpingField~~

~~The algorithms are sufficiently complicated to make it difficult to generate meaningful random inputs that properly test the features showcased here. It is particularly difficult in the case of the final ColorMapOptimization unit test.~~

~~I am creating this PR with the request for suggestions on how to properly initialize the inputs. I will update these tests accordingly.~~

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/605)

### CODE REVIEW

**Comment by qianyizh** [comment]
@takanokage can you rebase this pr?
@yxlao @syncle can you two be the feature reviewer of this pr?

**Comment by syncle** [comment]
I reviewed #631 includes this PR.

**Comment by qianyizh** [comment]
Yeah, it is a bit chaotic. But I think @takanokage prefers the PRs to be reviewed in chronological order. It would be nice if you can move some of the review comments in this PR so he can address them here.

**Comment by takanokage** [comment]
I have reverted ColorMapOptimization to the original implementation with mostly hidden functions.
I have also disabled all ColorMapOptimization tests.

**Pull request merged**
