### PR TITLE
apply style globally and enable check-style on CI

### PR DESCRIPTION
**Pull request by yxlao**
Re-opening https://github.com/IntelVCL/Open3D/pull/641 after 0.5 release.
Addressed @syncle 's comment on #641 

---

# Documentation

Different `clang-format` versions may produce slightly different formatting results. For standardization, `clang-format` version `5.0` is required for formatting Open3D. 

The reason why version `5.0` is used is due to the following considerations:
- Ubuntu 16.04: 3.8 by default
- Ubuntu 18.04: 6.0 by default
- macOS Mojave: 8.0 by default when installed with homebrew
- Windows: version <= 7.0 all available from from [LLVM Download Page](http://releases.llvm.org/download.html) )
- Travis CI 14.04: only works for 5.0 or lower. Installation error for 6.0 or higher. 

Verion 5.0 is chosen for full support across different platforms. To ensure compatibility, the following installation methods are manually tested on different platforms respectively.

## 1. Installing `clang-format-5.0`
By default, the make system tries to detect either  `clang-format-5.0` or  `clang-format`  from PATH. 

### 1.1 Ubuntu

**Ubuntu 14.04**
```bash
sudo apt update
sudo apt install wget software-properties-common -y
sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
sudo apt update
sudo apt install clang-format-5.0 -y
clang-format-5.0 --version
```

**Ubuntu 16.04**
```
sudo apt update
sudo apt install clang-format-5.0
clang-format-5.0 --version
```

**Ubuntu 18.04**
```
sudo apt update
sudo apt install clang-format-5.0
clang-format-5.0 --version
```

### 1.2 macOS
**Option 1**
```bash
curl https://gist.githubusercontent.com/ffeu/6ffb75d8e8c7d92c0fbeb4b036599c33/raw/7004b4955961528a22b4642c125d395ef7e054c7/clang-format@5.rb -o $(brew --repo)/Library/Taps/homebrew/homebrew-core/Formula/clang-format@5.rb
brew install clang-format@5
clang-format --version

# (Optional) If another clang-format version was previously installed, we can keep
# both versions and swtich the default to version 5
brew unlink clang-format
brew link clang-format@5

# (Optional) If you'd like to uninstall
brew uninstall clang-format@5
```

**Option 2**
Download clang-5.0 macOS package from  [LLVM Download Page](http://releases.llvm.org/download.html), unzip and add the directory containing clang-format to `PATH`.

### 1.3 Windows
Download clang-5.0 Windows package from  [LLVM Download Page](http://releases.llvm.org/download.html). During installation, select the option which allows adding clang toolchains to `PATH`.  After installation, open a CMD terminal and try
```batch
clang-format --version
```

## 2. Checking and applying format
Before starting, check your clang-format version by
```bash
clang-format --version
```

or, if installed as `clang-format-5.0`
```bash
clang-format-5.0 --version
```
 
and make sure that version `5.0` is installed.

### 2.1 Ubuntu & macOS
After CMake config, to check style, run
```bash
make check-style
```

After CMake config, to apply proper style, run
```bash
make apply-style
```

### 2.2 Windows
After CMake config, to check style, run
```batch
cmake --build . --target check-style
```

After CMake config, to apply proper style, run
```batch
cmake --build . --target apply-style
```

---

## Changes
- **apply style globally**
- **enable style check in Travis**
- changed AccessModifierOffset: -2
- check style in doc
- manual fix for shader
- manual fix for example helper print
- manual fix for off version header
- manual fix for UniformTSDFVolume.cpp
- manual fix for FastGlobalRegistration.cpp
- manual fix for GlobalOptimization.cpp
- manual fix for Eigen.cpp
- manual fix for src/Tools/*.cpp
- manual fix for Visualizer.cpp
- manual fix for VisualizerWithCustomAnimation.cpp
- manual fix for VisualizerWithEditing.cpp
- manual fix for src/Tools/ManuallyAlignPointCloud/*
- manual fix for docs/_static/C++/TestVisualizer.cpp
- manual fix for Voxelization.cpp

Also see https://github.com/IntelVCL/Open3D/pull/589 for details.

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/777)

### CODE REVIEW

**Comment by syncle** [comment]
Please let me know when the job is finished. Question - this is so huge PR, is there some way to quickly checking only really changed lines? I tried ``?w=1`` but it was not very useful in this PR.

**Comment by yxlao** [comment]
Thanks @syncle for reviewing this, will ping you know when it's finally ready. 

Currently, I am resolving the issue that different `clang-format` versions produces different formatting results. The solution is to fix to a certain version. The challenge is to find the most convenient version that works across Ubuntu / Mac / Windows. I'll add detailed documentation for instllation once the version is picked. 

The main files to review are:

- `.travis.yml`
- `util/scripts/run-travis.sh`

I'll update the above file list if there are further modifications.

**Comment by yxlao** [comment]
@syncle @takanokage @qianyizh ready for review now. Updates:

1. Selected clang-format 5.0 as standard. See https://github.com/IntelVCL/Open3D/pull/777#issue-245288252 on considerations.
2. **Added Windows support!** Changed shell scripts to cmaker scripts.
3. Added details documetation in `contribution.rst` on instllation & usage.

Please see https://github.com/IntelVCL/Open3D/pull/777#issuecomment-455931894 for the main files to review. Other files are auto-formated by the scripts.

**Comment by syncle** [comment]
Thanks @yxlao! This is very good in general, but I have some requests:

-----
1) ``/`` makes unnecessary line breaks. It happens when the divide operator is used.
2) Indent for function arguments are not consistent. For example, there are two styles
```
# style A
function(int a, double b, float c)
```
```
# style B
function(int a,
         double b, 
         float c)
```
I observe this PR changes A->B, but sometimes it also changes B->A. I checked some of them. Could you double-check?
3) There are some binary files (*.whl files) included in this PR. Please remove.

**Comment by yxlao** [comment]
@syncle, thanks for the review.

#### 1. "/" makes unnecessary line breaks. It happens when the divide operator is used.

(Update: as discussed offline, we can keep this as it is and try to refactor the code later.)

In fact not just "/", other binary operator such as "*" at that location caused the same issue. I tried to look into relavent options in https://clang.llvm.org/docs/ClangFormatStyleOptions.html, including:
- `BreakBeforeBinaryOperators`
- `AlignOperands`

However they don't seem to control this line break. 

My guess is that the reaons for this is that the LHS operand spans multiple lines, so clang-format decides that RHS operand must be in a new line. Conder the following examples:

Example 1
```cpp
// RHS argument in the same line
double is = (looooooooooooooooog_name + looooooooooooooooog_name +
             looooooooooooooooog_name) / 3.0;

// clang-format: RHS argument in a new line, not desirable
double is = (looooooooooooooooog_name + looooooooooooooooog_name +
             looooooooooooooooog_name) /
            3.0;
```

Example 2
```cpp
// RHS argument in the same line
double is = (looooooooooooooooog_name + looooooooooooooooog_name +
             looooooooooooooooog_name) / (looooooooooooooooog_name +
             looooooooooooooooog_name + looooooooooooooooog_name);

// clang-format: RHS argument in a new line, desirable
double is = (looooooooooooooooog_name + looooooooooooooooog_name +
             looooooooooooooooog_name) /
            (looooooooooooooooog_name + looooooooooooooooog_name +
             looooooooooooooooog_name);
```



#### 2. Indent for function arguments are not consistent.

Fixed in https://github.com/IntelVCL/Open3D/pull/777/commits/50e11e6ae2bdf3073f4d99e16ce5211757b0097f.

The change is to set
```
BinPackParameters: false
```

#### 3. There are some binary files (*.whl files) included in this PR. Please remove.
Removed.

**Pull request merged**
