### PR TITLE
Providing indices of original point cloud after voxel down sampling

### LINKED ISSUE #503: Voxel downsampling: pick one of the original points instead of the centroid
Is there a way to downsample such that the point generated by each voxel is one of the points occupying it and not the centroid of those points? The current API does not seem to support this.

### PR DESCRIPTION
**Pull request by syncle**
This PR resolves #503 and adds new voxel down sampling method that provides original point id of the higher resolution point cloud. This PR has minor working commits, so **PLEASE SQUASH MERGE**.

**Todo**
- Need to add tutorial documents regarding this PR.

--------
**Input**
- High resolution point cloud
- Downsampling voxel size

**Output**
- Downsampled point cloud
- Point ID of high resolution point cloud. It is stored in one of the 8 cubics.

---------
Example: example/Python/Advanced/downsample_and_trace.py

```
Original, # of points 196133

Scale 0.050000, # of points 4718

Scale 0.100000, # of points 1071
Downsampled points (the first 10 points)
[[ 3.15830265  1.23091875  1.55404802]
 [ 1.15019155  0.89679814  2.26257342]
 [ 1.02734375  2.39969158  1.33984375]
 [ 2.48562807  2.12299056  1.01483288]
 [ 2.68355304  1.91783643  1.13640535]
 [ 2.46068719  1.17869952  1.75616688]
 [ 0.62324467  0.94898347  2.43139524]
 [ 0.74280303  0.86925139  2.36048149]
 [ 1.72144064  1.75532196  1.71382546]
 [ 2.66417512  2.4178935   0.72384486]]
Index (the first 10 indices)
[[4704   -1   -1   -1   -1   -1   -1   -1]
 [  -1   -1 4700   -1   -1   -1   -1   -1]
 [  -1   -1   -1   -1   -1   -1   -1 4614]
 [  -1   -1   -1   -1 4642 4609   -1   -1]
 [  -1   -1   -1   -1   -1   -1 4577   -1]
 [  -1   -1 4572   -1   -1   -1   -1   -1]
 [  -1   -1   -1   -1   -1 4617   -1   -1]
 [4504   -1 4440   -1   -1   -1   -1   -1]
 [  -1 4413   -1 4688   -1 4640   -1 4538]
 [  -1   -1   -1   -1   -1   -1 4229   -1]]

Scale 0.200000, # of points 297
Downsampled points (the first 10 points)
[[ 2.37192896  1.80127229  1.54403037]
 [ 2.27234668  2.00572502  0.92277721]
 [ 2.03121165  2.41904989  0.68863835]
 [ 1.71782525  2.15832733  1.75750927]
 [ 2.6336108   2.39659757  1.4421798 ]
 [ 1.83564035  2.23317936  1.96058169]
 [ 1.23458708  2.39338665  1.64436995]
 [ 2.43452066  2.40371828  1.44280625]
 [ 1.83403653  2.40104516  1.64247116]
 [ 1.42933053  2.38599974  1.8414391 ]]
Index (the first 10 indices)
[[  -1   -1   -1   -1   -1   -1 1063   -1]
 [  -1   -1   -1   -1   -1   -1   -1 1048]
 [  -1   -1   -1   -1  958 1062   -1   -1]
 [  -1   -1   -1  951   -1   -1   -1   -1]
 [  -1   -1 1015  976   -1   -1  898 1018]
 [ 890  897   -1   -1   -1   -1   -1   -1]
 [  -1   -1  966  866   -1   -1  959  930]
 [  -1   -1 1067  832   -1   -1  998  911]
 [  -1   -1  831  953   -1   -1  909 1055]
 [  -1   -1 1036  760   -1   -1 1006  967]]
```

---
This change is [Reviewable](https://reviewable.io/reviews/intelvcl/open3d/619)

### CODE REVIEW

**Comment by qianyizh** [comment]
@syncle somehow there are some conflicts. Can you resolve them?
Otherwise, it is a pretty straightforward PR and can be merged once the conflicts are resolved.

**Comment by syncle** [comment]
Sure. I am working for avoiding conflicts. Please do not merge until all the tests are passed.

**Comment by lvgeng** [comment]
Em... I wish to use this. But which function should I call?
>
>open3d.geometry.voxel_down_sample_and_trace(input, voxel_size, min_bound, max_bound, approximate_class=False)
>
http://www.open3d.org/docs/release/python_api/open3d.geometry.voxel_down_sample_and_trace.html
seems to be the one, but I am confused about the returned numpy array. What does it mean?

**Comment by HM102** [comment]
I would also like to know what does the cubic_id represent? the index of the points used to average the downsampled  point? @syncle

**Pull request merged**
